trigger: none

pr: none

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Twilio.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Twilio\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      versionReference: "UiPath.Twilio.Activitie/Properties/AssemblyInfo.cs"


      