trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Twilio/*

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Twilio/*
      
jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Twilio.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "Any CPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Twilio\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      versionReference: "UiPath.Twilio.Activitie/Properties/AssemblyInfo.cs"
      